version: '3.7'

services:
  web-server:
    container_name: web-server
    image: web-server
    restart: always
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"

