version: '3.7'

services:
  web-server:
    container_name: web-server
    image: web-server
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - log_web:/var/log
      - source_code:/var/www/html

volumes:
  log_web:
  source_code:
